# --------------------------------------------------------------------------------------
# This file is part of qpe-toolbox.
#
# SPDX-License-Identifier: Apache-2.0
# Licensed under the Apache License, Version 2.0. See LICENSE.txt and NOTICE.txt in the
# project root.
#
# --------------------------------------------------------------------------------------

import time

import numpy as np

from qpe_toolbox import EXACT

from .hadamard_test import run_hadamard_test


def robust_phase_estimation(
    H,
    psi0,
    n_repetitions,
    n_steps,
    n_shots,
    *,
    t0=1.0,
    trotter_order=1,
    verbosity=0,
    rng=None,
):
    r"""
    Perform the Robust Phase Estimation (RPE) algorithm.

    This routine estimates the phase associated with the unitary
    time evolution generated by a Hamiltonian using a sequence of
    Hadamard tests at increasing evolution times.

    The algorithm estimates the phase :math:`\varphi = E_0 t_0` accumulated over
    the base evolution time :math:`t_0`. It refines this estimate over
    ``n_repetitions`` iterations indexed by :math:`m = 0, 1, \dots, M-1`, using
    the evolution time :math:`t_0 2^m` at iteration :math:`m` and gaining one bit
    of precision per iteration. The final estimate satisfies
    :math:`d(\theta, E_0 t_0) \leq 2^{-(M-1)}\pi/3` with :math:`M` the number of
    repetitions. Recover the energy as :math:`E_0 = \theta / t_0`.

    Parameters
    ----------
    H : Hamiltonian
        Hamiltonian object from the ``Hamiltonian`` class.
    psi0 : :quimb-api:`MatrixProductState`
        Initial quantum state :math:`\ket{\psi_0}` of the system.
    n_repetitions : int
        Number of RPE iterations :math:`M`. Iterations are indexed by
        :math:`m = 0, 1, \dots, M-1` with evolution time :math:`t_0 2^m`, and
        each iteration adds one bit of precision. To reach a precision of order
        :math:`\varepsilon`, take :math:`M = \lceil \log_2 \varepsilon^{-1}
        \rceil`; the guaranteed bound is then :math:`2^{-(M-1)}\pi/3 \simeq
        2\varepsilon`.
    n_steps : int or qpe_toolbox.EXACT
        Number of Trotter steps used to approximate the time evolution.
        Use ``EXACT`` for exact time evolution.
    n_shots : int or EXACT
        Number of measurement shots used in the Hadamard test.
        Use ``EXACT`` to compute probabilities exactly.
    t0 : float, default ``1.0``
        Base evolution time; the phase estimated is :math:`\varphi = E_0 t_0`.
        Choose :math:`t_0` so that :math:`|E_0 t_0| < \pi`, otherwise the
        :math:`m = 0` phase is ambiguous.
    trotter_order : int, default ``1``
        Order of the Trotter-Suzuki decomposition. Ignored when
        `n_steps is EXACT`.
    verbosity : int, default ``0``
        Verbosity level. If >= 1, print intermediate phase estimates.
    rng : :numpy-random:`numpy.random.Generator <generator>`, optional
        Random generator for the Hadamard-test sampling. Ignored when
        ``n_shots`` is ``EXACT``.

    Returns
    -------
    theta_values : (M,) array of float
        Phase estimates :math:`\theta_0, \dots, \theta_{M-1}` of
        :math:`\varphi = E_0 t_0`, one per iteration. The last element is the
        most accurate estimate; recover the energy as :math:`\theta / t_0`.
    """
    st = time.time()
    if rng is None:
        rng = np.random.default_rng()

    theta_values = np.zeros(n_repetitions)
    if verbosity >= 1:
        print(f"m \t {'phi_m':<6} \t {'theta_m':<6} \t {'time (s)'}")
    for m in range(n_repetitions):
        evolution_time = t0 * 2**m
        n_steps_m = EXACT if n_steps is EXACT else n_steps * 2**m
        phi_m = rpe_get_hadamard_output(
            H,
            psi0,
            evolution_time,
            n_steps_m,
            n_shots,
            trotter_order=trotter_order,
            rng=rng,
        )

        if m == 0:
            # initialization theta_{-1} = 0, hence theta_0 = phi_0
            theta_values[m] = phi_m
        else:
            # refine the previous guess theta_{m-1} = theta_list[m - 1]
            theta_values[m] = rpe_update_theta(phi_m, theta_values[m - 1], m)

        if verbosity >= 1:
            et = time.time() - st
            print(
                f"{m} \t {np.round(phi_m, 4): 6} \t {np.round(theta_values[m], 4): 6}"
                f" \t {et:<6.1f}"
            )

    return theta_values


def rpe_get_hadamard_output(
    H, psi0, evolution_time, n_steps, n_shots, *, trotter_order=1, rng=None
):
    r"""
    Estimate the phase of :math:`\bra{\psi_0}\exp(-i H t)\ket{\psi_0}` using Hadamard tests.

    This function computes the phase corresponding to the unitary
    evolution over time :math:`t` by evaluating real and imaginary parts
    via Hadamard tests.

    Parameters
    ----------
    H : Hamiltonian
        Hamiltonian object defining the system.
    psi0 : :quimb-api:`MatrixProductState`
        Initial quantum state :math:`\ket{\psi_0}`.
    evolution_time : float
        Time to evolve in :math:`\exp(-iHt)`.
    n_steps : int or qpe_toolbox.EXACT
        Number of Trotter steps. Use ``EXACT`` for exact time evolution.
    n_shots : int or qpe_toolbox.EXACT
        Number of measurement shots used in the Hadamard test.
        Use ``EXACT`` to compute probabilities exactly.
    trotter_order : int, default ``1``
        Order of the Trotter-Suzuki decomposition.
    rng : :numpy-random:`numpy.random.Generator <generator>`, optional
        Random generator threaded through the two Hadamard tests, so the real
        and imaginary parts use independent samples. Ignored when ``n_shots``
        is ``EXACT``.

    Returns
    -------
    phi_m : float
        Estimated phase angle in radians.
    """
    # at step m, we typically expect evolution_time = t0*2**m, but this is not a requirement
    n_qubits = H.n_qubits
    phys_reg = list(range(1, n_qubits + 1))
    if n_steps is EXACT:
        U_m = H.get_U_exact(evolution_time, phys_reg, controls=(0,))
    else:
        if not (n_steps > 0):
            raise ValueError("Can only evolve for strictly positive n_steps")
        dt = evolution_time / n_steps
        U_m = [H.get_trotter_step(dt, phys_reg, trotter_order)] * n_steps
    X_m = run_hadamard_test(psi0, U_m, 0, n_shots, rng=rng)
    Y_m = run_hadamard_test(psi0, U_m, -np.pi / 2, n_shots, rng=rng)
    Z_m = X_m + 1j * Y_m
    return -np.angle(Z_m)


def angular_distance(phi, theta):
    """
    Compute the angular distance between two angles.

    The distance is defined modulo π and lies in the interval [0, π].

    Parameters
    ----------
    phi : float or array of float
        First angle in radians.
    theta : float or array of float
        Second angle in radians.

    Returns
    -------
    d : float or array of float
        Angular distance between ``phi`` and ``theta``.
    """
    K = np.rint((phi - theta) / (2 * np.pi))
    return np.abs(phi - theta - K * 2 * np.pi)


def rpe_update_theta(phi_m, theta_ref, m):
    r"""
    Refine the phase estimate at iteration ``m``.

    Parameters
    ----------
    phi_m : float
        Phase estimate at iteration ``m``, in radians.
    theta_ref : float
        Reference angle (previous phase estimate :math:`\theta_{m-1}`).
    m : int
        Iteration index.

    Returns
    -------
    theta_m : float
        Refined phase estimate, the candidate nearest to ``theta_ref``, wrapped
        into :math:`[-\pi, \pi)`.
    """
    # The candidates (phi_m + 2*pi*k) / 2^m form a uniform grid on the circle.
    # Grid point closest (modulo :math:`2\pi`) to ``theta_ref`` is obtained by rounding
    # the float (2^m theta_ref - phi_m) / 2pi
    k = round((2**m * theta_ref - phi_m) / (2 * np.pi))
    theta_m = (phi_m + 2 * np.pi * k) / 2**m
    return (theta_m + np.pi) % (2 * np.pi) - np.pi
