# --------------------------------------------------------------------------------------
# This file is part of qpe-toolbox.
#
# SPDX-License-Identifier: Apache-2.0
# Licensed under the Apache License, Version 2.0. See LICENSE.txt and NOTICE.txt in the
# project root.
#
# --------------------------------------------------------------------------------------

import time

import numpy as np

from qpe_toolbox import EXACT

from .hadamard_test import run_hadamard_test


def robust_phase_estimation(
    H,
    psi0,
    n_repetitions,
    sign_E0,
    n_steps,
    n_shots,
    *,
    trotter_order=2,
    verbosity=0,
    rng=None,
):
    r"""
    Perform the Robust Phase Estimation (RPE) algorithm.

    This routine estimates the phase associated with the unitary
    time evolution generated by a Hamiltonian using a sequence of
    Hadamard tests at increasing evolution times.

    The algorithm refines the phase estimate over ``n_repetitions`` iterations
    indexed by :math:`m = 0, 1, \dots, M-1`, using the evolution time
    :math:`2^m` at iteration :math:`m` and gaining one bit of precision per
    iteration. The final estimate satisfies :math:`d(\theta, E_0) \leq
    2^{-(M-1)}\pi/3` with :math:`M` the number of repetitions.

    Parameters
    ----------
    H : Hamiltonian
        Hamiltonian object from the ``Hamiltonian`` class.
    psi0 : :quimb-api:`MatrixProductState`
        Initial quantum state :math:`\ket{\psi_0}` of the system.
    n_repetitions : int
        Number of RPE iterations :math:`M`. Iterations are indexed by
        :math:`m = 0, 1, \dots, M-1` with evolution time :math:`2^m`, and each
        iteration adds one bit of precision. To reach a target precision
        :math:`\varepsilon`, take :math:`M = \lceil \log_2 \varepsilon^{-1}
        \rceil`.
    sign_E0 : float
        Sign of the target energy eigenvalue.
    n_steps : int or qpe_toolbox.EXACT
        Number of Trotter steps used to approximate the time evolution.
        Use ``EXACT`` for exact time evolution.
    n_shots : int or EXACT
        Number of measurement shots used in the Hadamard test.
        Use ``EXACT`` to compute probabilities exactly.
    trotter_order : int, default ``2``
        Order of the Trotter-Suzuki decomposition.
    verbosity : int, default ``0``
        Verbosity level. If >= 1, print intermediate phase estimates.
    rng : :numpy-random:`numpy.random.Generator <generator>`, optional
        Random generator for the Hadamard-test sampling. Pass a seeded
        generator (e.g. ``numpy.random.default_rng(42)``) for deterministic
        results. A single generator is threaded through every iteration.
        Ignored when ``n_shots`` is ``EXACT``.

    Returns
    -------
    theta_list : list of float
        Phase estimates :math:`\theta_0, \dots, \theta_{M-1}`, one per
        iteration. The last element is the most accurate estimate.
    """
    if abs(abs(sign_E0) - 1.0) > 1e-12:
        raise ValueError("sign_E0 must be +-1")

    st = time.time()
    if rng is None:
        rng = np.random.default_rng()

    theta_list = []
    if verbosity >= 1:
        print(f"m \t {'phi_m':<6} \t {'theta_m':<6} \t {'time (s)'}")
    for m in range(n_repetitions):
        if n_steps is EXACT:
            phi_m = rpe_get_hadamard_output(H, psi0, m, n_steps, n_shots, rng=rng)
        else:
            phi_m = rpe_get_hadamard_output(
                H,
                psi0,
                m,
                n_steps * 2**m,
                n_shots,
                trotter_order=trotter_order,
                rng=rng,
            )

        if m == 0:
            # initialization theta_{-1} = 0, hence theta_0 = phi_0
            theta_m = phi_m
        else:
            # refine the previous guess theta_{m-1} = theta_list[m - 1]
            S_m = (phi_m + sign_E0 * 2 * np.pi * np.arange(2**m)) / 2**m
            theta_m, _d_min = rpe_update_theta(S_m, theta_list[m - 1])

        if verbosity >= 1:
            et = time.time() - st
            print(
                f"{m} \t {np.round(phi_m, 4):<6} \t {np.round(theta_m, 4):<6} \t {et:<6.1f}"
            )

        theta_list.append(theta_m)

    return theta_list


def rpe_get_hadamard_output(H, psi0, m, n_steps, n_shots, *, trotter_order=2, rng=None):
    r"""
    Estimate the phase of :math:`\bra{\psi_0}\exp(-i H 2^m)\ket{\psi_0}` using Hadamard tests.

    This function computes the phase corresponding to the unitary
    evolution over time :math:`2^m` by evaluating real and imaginary parts
    via Hadamard tests.

    Parameters
    ----------
    H : Hamiltonian
        Hamiltonian object defining the system.
    psi0 : :quimb-api:`MatrixProductState`
        Initial quantum state :math:`\ket{\psi_0}`.
    m : int
        Iteration index corresponding to evolution time ``2**m``.
    n_steps : int or qpe_toolbox.EXACT
        Number of Trotter steps. Use ``EXACT`` for exact time evolution.
    n_shots : int or qpe_toolbox.EXACT
        Number of measurement shots used in the Hadamard test.
        Use ``EXACT`` to compute probabilities exactly.
    trotter_order : int, default ``2``
        Order of the Trotter-Suzuki decomposition.
    rng : :numpy-random:`numpy.random.Generator <generator>`, optional
        Random generator threaded through the two Hadamard tests, so the real
        and imaginary parts use independent samples. Ignored when ``n_shots``
        is ``EXACT``.

    Returns
    -------
    phi_m : float
        Estimated phase angle in radians.
    """
    n_qubits = H.n_qubits
    phys_reg = list(range(1, n_qubits + 1))
    evolution_time = 2**m
    if n_steps is EXACT:
        U_m = H.get_U_exact(evolution_time, phys_reg, controls=(0,))
    else:
        if not (n_steps > 0):
            raise ValueError("Can only evolve for strictly positive n_steps")
        dt = evolution_time / n_steps
        U_m = [H.get_trotter_step(dt, phys_reg, trotter_order)] * n_steps
    X_m = run_hadamard_test(psi0, U_m, 0, n_shots, rng=rng)
    Y_m = run_hadamard_test(psi0, U_m, -np.pi / 2, n_shots, rng=rng)
    Z_m = X_m + 1j * Y_m
    return -np.angle(Z_m)


def rpe_distance(phi, theta):
    """
    Compute the angular distance between two angles.

    The distance is defined modulo π and lies in the interval [0, π).

    Parameters
    ----------
    phi : float or array of float
        First angle in radians.
    theta : float or array of float
        Second angle in radians.

    Returns
    -------
    d : float or array of float
        Angular distance between ``phi`` and ``theta``.
    """
    sign = np.sign(phi - theta)
    K = np.floor(np.abs(phi - theta) / (2 * np.pi) + 1 / 2)
    return np.abs(phi - theta - K * sign * 2 * np.pi)


def rpe_update_theta(S, theta_ref):
    """
    Find the angle in a set closest to a reference angle.

    The comparison is performed using the angular distance
    modulo 2π.

    Parameters
    ----------
    S : list of float
        Candidate angles.
    theta_ref : float
        Reference angle.

    Returns
    -------
    theta_min : float
        Angle in ``S`` closest to ``theta_ref``.
    d_min : float
        Corresponding minimal angular distance.
    """
    d_min = rpe_distance(S[0], theta_ref)
    theta_min = S[0]
    for theta in S[1:]:
        if (rpe_distance(theta, theta_ref) <= d_min) and (-np.pi <= theta < np.pi):
            d_min = rpe_distance(theta, theta_ref)
            theta_min = theta
    return theta_min, d_min
