name: Documentation

on: [pull_request]

jobs:
  build-doc:
    runs-on: ubuntu-slim
    steps:
    - uses: actions/checkout@v6

    - name: Install uv
      uses: astral-sh/setup-uv@v7
      with:
        python-version: "3.13"

    - name: Install the project
      run: uv sync --locked --group=docs

    # This job does not run the notebooks as it is expensive
    # it just checks the doc can be constructed
    # docs/Makefile contains the same steps. We do not use make here to get
    # well separated steps and cleaner logs.
    # // is fine here, this is jupytext syntax
    - name: Convert examples
      run: uv run --no-sync jupytext examples/*py --to ../docs/source/customapi/tutorials//ipynb

    - name: Copy figures to docs
      run: cp -r examples/figures docs/source/customapi/tutorials

    - name: Build doc
      run: uv run --no-sync sphinx-build -b html -W docs/source docs/build

      # upload doc as artifact to be able to check result.
      # doc is not deployed: working document available for 2 days from job link
    - name: Upload doc
      uses: actions/upload-artifact@v6
      with:
        name: built_doc_artifact
        path: docs/build
        if-no-files-found: error
        retention-days: 2
