name: Lint - other

on: [pull_request]

jobs:
  pre-commit:
    runs-on: ubuntu-slim
    steps:
    - uses: actions/checkout@v6

    - uses: ./.github/actions/setup

    - name: Install the project
      run: uv sync --locked --only-group=lint

    - name: Run pre-commit
      run: SKIP=ruff-check,ruff-format,format-examples uv run pre-commit run --all-files
