name: Test

on: [pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6

    - uses: ./.github/actions/setup

    - name: Install the project
      run: uv sync --locked --group=test --no-default-groups --extra recommended

    - name: Run tests
      run: uv run pytest -n auto -v --deselect tests/test_examples.py --durations=0 --durations-min=0.5 --color=yes --cov-report=html

    - name: upload HTML coverage
      uses: actions/upload-artifact@v6
      with:
        name: coverage-html
        path: htmlcov
        if-no-files-found: error
        retention-days: 5
        overwrite: true
