name: Lint python

on: [pull_request]

jobs:
  ruff-check:
    runs-on: ubuntu-slim
    steps:
    - uses: actions/checkout@v6

    - name: Install uv
      uses: astral-sh/setup-uv@v7
      with:
        python-version: "3.13"

    - name: Install ruff
      run: uv sync --locked --only-group=lint

    - name: ruff check
      run: uv run --no-sync ruff check
