name: Lint python

on: [pull_request]

jobs:
  ruff-check:
    runs-on: ubuntu-slim
    steps:
    - uses: actions/checkout@v6

    - uses: ./.github/actions/setup

    - name: Install ruff
      run: uv sync --locked --only-group=lint

    - name: ruff check
      run: uv run ruff check
